package net.greenjab.nekomasfixed.util;

import net.greenjab.nekomasfixed.registry.registries.BlockRegistry;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import java.util.EnumMap;

public class BlockDyeMap {
    public static final EnumMap<AllDyes, Block> BRICKS = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BRICK_SLAB = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BRICK_STAIRS = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BRICK_WALL = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> TERRACOTTA = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> STAINED_GLASS = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> STAINED_GLASS_PANE = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> WOOL = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> SPOTTED_WOOL = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CARPET = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> SPOTTED_CARPET = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> GLAZED_TERRACOTTA = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CANDLE = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CONCRETE = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CONCRETE_POWDER = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> FROGLIGHT = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> SHULKER_BOX = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BED = new EnumMap<>(AllDyes.class);
    static {
        WOOL.put(AllDyes.WHITE, Blocks.WOOL.white());
        WOOL.put(AllDyes.ORANGE, Blocks.WOOL.orange());
        WOOL.put(AllDyes.MAGENTA, Blocks.WOOL.magenta());
        WOOL.put(AllDyes.LIGHT_BLUE, Blocks.WOOL.lightBlue());
        WOOL.put(AllDyes.YELLOW, Blocks.WOOL.yellow());
        WOOL.put(AllDyes.LIME, Blocks.WOOL.lime());
        WOOL.put(AllDyes.PINK, Blocks.WOOL.pink());
        WOOL.put(AllDyes.GRAY, Blocks.WOOL.gray());
        WOOL.put(AllDyes.LIGHT_GRAY, Blocks.WOOL.lightGray());
        WOOL.put(AllDyes.CYAN, Blocks.WOOL.cyan());
        WOOL.put(AllDyes.PURPLE, Blocks.WOOL.purple());
        WOOL.put(AllDyes.BLUE, Blocks.WOOL.blue());
        WOOL.put(AllDyes.BROWN, Blocks.WOOL.brown());
        WOOL.put(AllDyes.GREEN, Blocks.WOOL.green());
        WOOL.put(AllDyes.RED, Blocks.WOOL.red());
        WOOL.put(AllDyes.BLACK, Blocks.WOOL.black());
        WOOL.put(AllDyes.AMBER, BlockRegistry.AMBER_WOOL);
        WOOL.put(AllDyes.AQUA, BlockRegistry.AQUA_WOOL);
        WOOL.put(AllDyes.INDIGO, BlockRegistry.INDIGO_WOOL);
        WOOL.put(AllDyes.MAROON, BlockRegistry.MAROON_WOOL);

        SPOTTED_WOOL.put(AllDyes.WHITE, BlockRegistry.WHITE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.ORANGE, BlockRegistry.ORANGE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.YELLOW, BlockRegistry.YELLOW_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.LIME, BlockRegistry.LIME_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.PINK, BlockRegistry.PINK_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.GRAY, BlockRegistry.GRAY_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.CYAN, BlockRegistry.CYAN_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.PURPLE, BlockRegistry.PURPLE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.BLUE, BlockRegistry.BLUE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.BROWN, BlockRegistry.BROWN_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.GREEN, BlockRegistry.GREEN_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.RED, BlockRegistry.RED_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.BLACK, BlockRegistry.BLACK_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.AMBER, BlockRegistry.AMBER_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.AQUA, BlockRegistry.AQUA_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.INDIGO, BlockRegistry.INDIGO_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.MAROON, BlockRegistry.MAROON_SPOTTED_WOOL);

        CONCRETE.put(AllDyes.WHITE, Blocks.CONCRETE.white());
        CONCRETE.put(AllDyes.ORANGE, Blocks.CONCRETE.orange());
        CONCRETE.put(AllDyes.MAGENTA, Blocks.CONCRETE.magenta());
        CONCRETE.put(AllDyes.LIGHT_BLUE, Blocks.CONCRETE.lightBlue());
        CONCRETE.put(AllDyes.YELLOW, Blocks.CONCRETE.yellow());
        CONCRETE.put(AllDyes.LIME, Blocks.CONCRETE.lime());
        CONCRETE.put(AllDyes.PINK, Blocks.CONCRETE.pink());
        CONCRETE.put(AllDyes.GRAY, Blocks.CONCRETE.gray());
        CONCRETE.put(AllDyes.LIGHT_GRAY, Blocks.CONCRETE.lightGray());
        CONCRETE.put(AllDyes.CYAN, Blocks.CONCRETE.cyan());
        CONCRETE.put(AllDyes.PURPLE, Blocks.CONCRETE.purple());
        CONCRETE.put(AllDyes.BLUE, Blocks.CONCRETE.blue());
        CONCRETE.put(AllDyes.BROWN, Blocks.CONCRETE.brown());
        CONCRETE.put(AllDyes.GREEN, Blocks.CONCRETE.green());
        CONCRETE.put(AllDyes.RED, Blocks.CONCRETE.red());
        CONCRETE.put(AllDyes.BLACK, Blocks.CONCRETE.black());
        CONCRETE.put(AllDyes.AMBER, BlockRegistry.AMBER_CONCRETE);
        CONCRETE.put(AllDyes.AQUA, BlockRegistry.AQUA_CONCRETE);
        CONCRETE.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CONCRETE);
        CONCRETE.put(AllDyes.MAROON, BlockRegistry.MAROON_CONCRETE);

        CONCRETE_POWDER.put(AllDyes.WHITE, Blocks.CONCRETE_POWDER.white());
        CONCRETE_POWDER.put(AllDyes.ORANGE, Blocks.CONCRETE_POWDER.orange());
        CONCRETE_POWDER.put(AllDyes.MAGENTA, Blocks.CONCRETE_POWDER.magenta());
        CONCRETE_POWDER.put(AllDyes.LIGHT_BLUE, Blocks.CONCRETE_POWDER.lightBlue());
        CONCRETE_POWDER.put(AllDyes.YELLOW, Blocks.CONCRETE_POWDER.yellow());
        CONCRETE_POWDER.put(AllDyes.LIME, Blocks.CONCRETE_POWDER.lime());
        CONCRETE_POWDER.put(AllDyes.PINK, Blocks.CONCRETE_POWDER.pink());
        CONCRETE_POWDER.put(AllDyes.GRAY, Blocks.CONCRETE_POWDER.gray());
        CONCRETE_POWDER.put(AllDyes.LIGHT_GRAY, Blocks.CONCRETE_POWDER.lightGray());
        CONCRETE_POWDER.put(AllDyes.CYAN, Blocks.CONCRETE_POWDER.cyan());
        CONCRETE_POWDER.put(AllDyes.PURPLE, Blocks.CONCRETE_POWDER.purple());
        CONCRETE_POWDER.put(AllDyes.BLUE, Blocks.CONCRETE_POWDER.blue());
        CONCRETE_POWDER.put(AllDyes.BROWN, Blocks.CONCRETE_POWDER.brown());
        CONCRETE_POWDER.put(AllDyes.GREEN, Blocks.CONCRETE_POWDER.green());
        CONCRETE_POWDER.put(AllDyes.RED, Blocks.CONCRETE_POWDER.red());
        CONCRETE_POWDER.put(AllDyes.BLACK, Blocks.CONCRETE_POWDER.black());
        CONCRETE_POWDER.put(AllDyes.AMBER, BlockRegistry.AMBER_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.AQUA, BlockRegistry.AQUA_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.MAROON, BlockRegistry.MAROON_CONCRETE_POWDER);

        CARPET.put(AllDyes.WHITE, Blocks.CARPET.white());
        CARPET.put(AllDyes.ORANGE, Blocks.CARPET.orange());
        CARPET.put(AllDyes.MAGENTA, Blocks.CARPET.magenta());
        CARPET.put(AllDyes.LIGHT_BLUE, Blocks.CARPET.lightBlue());
        CARPET.put(AllDyes.YELLOW, Blocks.CARPET.yellow());
        CARPET.put(AllDyes.LIME, Blocks.CARPET.lime());
        CARPET.put(AllDyes.PINK, Blocks.CARPET.pink());
        CARPET.put(AllDyes.GRAY, Blocks.CARPET.gray());
        CARPET.put(AllDyes.LIGHT_GRAY, Blocks.CARPET.lightGray());
        CARPET.put(AllDyes.CYAN, Blocks.CARPET.cyan());
        CARPET.put(AllDyes.PURPLE, Blocks.CARPET.purple());
        CARPET.put(AllDyes.BLUE, Blocks.CARPET.blue());
        CARPET.put(AllDyes.BROWN, Blocks.CARPET.brown());
        CARPET.put(AllDyes.GREEN, Blocks.CARPET.green());
        CARPET.put(AllDyes.RED, Blocks.CARPET.red());
        CARPET.put(AllDyes.BLACK, Blocks.CARPET.black());
        CARPET.put(AllDyes.AMBER, BlockRegistry.AMBER_CARPET);
        CARPET.put(AllDyes.AQUA, BlockRegistry.AQUA_CARPET);
        CARPET.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CARPET);
        CARPET.put(AllDyes.MAROON, BlockRegistry.MAROON_CARPET);

        SPOTTED_CARPET.put(AllDyes.WHITE, BlockRegistry.WHITE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.ORANGE, BlockRegistry.ORANGE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.YELLOW, BlockRegistry.YELLOW_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.LIME, BlockRegistry.LIME_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.PINK, BlockRegistry.PINK_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.GRAY, BlockRegistry.GRAY_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.CYAN, BlockRegistry.CYAN_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.PURPLE, BlockRegistry.PURPLE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.BLUE, BlockRegistry.BLUE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.BROWN, BlockRegistry.BROWN_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.GREEN, BlockRegistry.GREEN_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.RED, BlockRegistry.RED_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.BLACK, BlockRegistry.BLACK_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.AMBER, BlockRegistry.AMBER_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.AQUA, BlockRegistry.AQUA_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.INDIGO, BlockRegistry.INDIGO_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.MAROON, BlockRegistry.MAROON_SPOTTED_CARPET);

        CANDLE.put(AllDyes.WHITE, Blocks.CANDLE);
        CANDLE.put(AllDyes.ORANGE, Blocks.CANDLE);
        CANDLE.put(AllDyes.MAGENTA, Blocks.CANDLE);
        CANDLE.put(AllDyes.LIGHT_BLUE, Blocks.CANDLE);
        CANDLE.put(AllDyes.YELLOW, Blocks.CANDLE);
        CANDLE.put(AllDyes.LIME, Blocks.CANDLE);
        CANDLE.put(AllDyes.PINK, Blocks.CANDLE);
        CANDLE.put(AllDyes.GRAY, Blocks.CANDLE);
        CANDLE.put(AllDyes.LIGHT_GRAY, Blocks.CANDLE);
        CANDLE.put(AllDyes.CYAN, Blocks.CANDLE);
        CANDLE.put(AllDyes.PURPLE, Blocks.CANDLE);
        CANDLE.put(AllDyes.BLUE, Blocks.CANDLE);
        CANDLE.put(AllDyes.BROWN, Blocks.CANDLE);
        CANDLE.put(AllDyes.GREEN, Blocks.CANDLE);
        CANDLE.put(AllDyes.RED, Blocks.CANDLE);
        CANDLE.put(AllDyes.BLACK, Blocks.CANDLE);
        CANDLE.put(AllDyes.AMBER, BlockRegistry.AMBER_CANDLE);
        CANDLE.put(AllDyes.AQUA, BlockRegistry.AQUA_CANDLE);
        CANDLE.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CANDLE);
        CANDLE.put(AllDyes.MAROON, BlockRegistry.MAROON_CANDLE);

        GLAZED_TERRACOTTA.put(AllDyes.WHITE, Blocks.GLAZED_TERRACOTTA.white());
        GLAZED_TERRACOTTA.put(AllDyes.ORANGE, Blocks.GLAZED_TERRACOTTA.orange());
        GLAZED_TERRACOTTA.put(AllDyes.MAGENTA, Blocks.GLAZED_TERRACOTTA.magenta());
        GLAZED_TERRACOTTA.put(AllDyes.LIGHT_BLUE, Blocks.GLAZED_TERRACOTTA.lightBlue());
        GLAZED_TERRACOTTA.put(AllDyes.YELLOW, Blocks.GLAZED_TERRACOTTA.yellow());
        GLAZED_TERRACOTTA.put(AllDyes.LIME, Blocks.GLAZED_TERRACOTTA.lime());
        GLAZED_TERRACOTTA.put(AllDyes.PINK, Blocks.GLAZED_TERRACOTTA.pink());
        GLAZED_TERRACOTTA.put(AllDyes.GRAY, Blocks.GLAZED_TERRACOTTA.gray());
        GLAZED_TERRACOTTA.put(AllDyes.LIGHT_GRAY, Blocks.GLAZED_TERRACOTTA.lightGray());
        GLAZED_TERRACOTTA.put(AllDyes.CYAN, Blocks.GLAZED_TERRACOTTA.cyan());
        GLAZED_TERRACOTTA.put(AllDyes.PURPLE, Blocks.GLAZED_TERRACOTTA.purple());
        GLAZED_TERRACOTTA.put(AllDyes.BLUE, Blocks.GLAZED_TERRACOTTA.blue());
        GLAZED_TERRACOTTA.put(AllDyes.BROWN, Blocks.GLAZED_TERRACOTTA.brown());
        GLAZED_TERRACOTTA.put(AllDyes.GREEN, Blocks.GLAZED_TERRACOTTA.green());
        GLAZED_TERRACOTTA.put(AllDyes.RED, Blocks.GLAZED_TERRACOTTA.red());
        GLAZED_TERRACOTTA.put(AllDyes.BLACK, Blocks.GLAZED_TERRACOTTA.black());
        GLAZED_TERRACOTTA.put(AllDyes.AMBER, BlockRegistry.AMBER_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.AQUA, BlockRegistry.AQUA_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.INDIGO, BlockRegistry.INDIGO_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.MAROON, BlockRegistry.MAROON_GLAZED_TERRACOTTA);

        BRICKS.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICKS);
        BRICKS.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICKS);
        BRICKS.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICKS);
        BRICKS.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICKS);
        BRICKS.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICKS);
        BRICKS.put(AllDyes.LIME, BlockRegistry.LIME_BRICKS);
        BRICKS.put(AllDyes.PINK, BlockRegistry.PINK_BRICKS);
        BRICKS.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICKS);
        BRICKS.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICKS);
        BRICKS.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICKS);
        BRICKS.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICKS);
        BRICKS.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICKS);
        BRICKS.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICKS);
        BRICKS.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICKS);
        BRICKS.put(AllDyes.RED, BlockRegistry.RED_BRICKS);
        BRICKS.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICKS);
        BRICKS.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICKS);
        BRICKS.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICKS);
        BRICKS.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICKS);
        BRICKS.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICKS);

        BRICK_SLAB.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.LIME, BlockRegistry.LIME_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.PINK, BlockRegistry.PINK_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.RED, BlockRegistry.RED_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICK_SLAB);

        BRICK_STAIRS.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.LIME, BlockRegistry.LIME_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.PINK, BlockRegistry.PINK_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.RED, BlockRegistry.RED_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICK_STAIRS);

        BRICK_WALL.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICK_WALL);
        BRICK_WALL.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICK_WALL);
        BRICK_WALL.put(AllDyes.LIME, BlockRegistry.LIME_BRICK_WALL);
        BRICK_WALL.put(AllDyes.PINK, BlockRegistry.PINK_BRICK_WALL);
        BRICK_WALL.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICK_WALL);
        BRICK_WALL.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICK_WALL);
        BRICK_WALL.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICK_WALL);
        BRICK_WALL.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICK_WALL);
        BRICK_WALL.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICK_WALL);
        BRICK_WALL.put(AllDyes.RED, BlockRegistry.RED_BRICK_WALL);
        BRICK_WALL.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICK_WALL);
        BRICK_WALL.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICK_WALL);
        BRICK_WALL.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICK_WALL);
        BRICK_WALL.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICK_WALL);
        BRICK_WALL.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICK_WALL);

        TERRACOTTA.put(AllDyes.WHITE, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.ORANGE, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.MAGENTA, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.LIGHT_BLUE, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.YELLOW, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.LIME, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.PINK, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.GRAY, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.LIGHT_GRAY, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.CYAN, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.PURPLE, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.BLUE, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.BROWN, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.GREEN, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.RED, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.BLACK, Blocks.TERRACOTTA);
        TERRACOTTA.put(AllDyes.AMBER, BlockRegistry.AMBER_TERRACOTTA);
        TERRACOTTA.put(AllDyes.AQUA, BlockRegistry.AQUA_TERRACOTTA);
        TERRACOTTA.put(AllDyes.INDIGO, BlockRegistry.INDIGO_TERRACOTTA);
        TERRACOTTA.put(AllDyes.MAROON, BlockRegistry.MAROON_TERRACOTTA);

        STAINED_GLASS.put(AllDyes.WHITE, Blocks.STAINED_GLASS.white());
        STAINED_GLASS.put(AllDyes.ORANGE, Blocks.STAINED_GLASS.orange());
        STAINED_GLASS.put(AllDyes.MAGENTA, Blocks.STAINED_GLASS.magenta());
        STAINED_GLASS.put(AllDyes.LIGHT_BLUE, Blocks.STAINED_GLASS.lightBlue());
        STAINED_GLASS.put(AllDyes.YELLOW, Blocks.STAINED_GLASS.yellow());
        STAINED_GLASS.put(AllDyes.LIME, Blocks.STAINED_GLASS.lime());
        STAINED_GLASS.put(AllDyes.PINK, Blocks.STAINED_GLASS.pink());
        STAINED_GLASS.put(AllDyes.GRAY, Blocks.STAINED_GLASS.gray());
        STAINED_GLASS.put(AllDyes.LIGHT_GRAY, Blocks.STAINED_GLASS.lightGray());
        STAINED_GLASS.put(AllDyes.CYAN, Blocks.STAINED_GLASS.cyan());
        STAINED_GLASS.put(AllDyes.PURPLE, Blocks.STAINED_GLASS.purple());
        STAINED_GLASS.put(AllDyes.BLUE, Blocks.STAINED_GLASS.blue());
        STAINED_GLASS.put(AllDyes.BROWN, Blocks.STAINED_GLASS.brown());
        STAINED_GLASS.put(AllDyes.GREEN, Blocks.STAINED_GLASS.green());
        STAINED_GLASS.put(AllDyes.RED, Blocks.STAINED_GLASS.red());
        STAINED_GLASS.put(AllDyes.BLACK, Blocks.STAINED_GLASS.black());
        STAINED_GLASS.put(AllDyes.AMBER, BlockRegistry.AMBER_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.AQUA, BlockRegistry.AQUA_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.INDIGO, BlockRegistry.INDIGO_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.MAROON, BlockRegistry.MAROON_STAINED_GLASS);

        STAINED_GLASS_PANE.put(AllDyes.WHITE, Blocks.STAINED_GLASS_PANE.white());
        STAINED_GLASS_PANE.put(AllDyes.ORANGE, Blocks.STAINED_GLASS_PANE.orange());
        STAINED_GLASS_PANE.put(AllDyes.MAGENTA, Blocks.STAINED_GLASS_PANE.magenta());
        STAINED_GLASS_PANE.put(AllDyes.LIGHT_BLUE, Blocks.STAINED_GLASS_PANE.lightBlue());
        STAINED_GLASS_PANE.put(AllDyes.YELLOW, Blocks.STAINED_GLASS_PANE.yellow());
        STAINED_GLASS_PANE.put(AllDyes.LIME, Blocks.STAINED_GLASS_PANE.lime());
        STAINED_GLASS_PANE.put(AllDyes.PINK, Blocks.STAINED_GLASS_PANE.pink());
        STAINED_GLASS_PANE.put(AllDyes.GRAY, Blocks.STAINED_GLASS_PANE.gray());
        STAINED_GLASS_PANE.put(AllDyes.LIGHT_GRAY, Blocks.STAINED_GLASS_PANE.lightGray());
        STAINED_GLASS_PANE.put(AllDyes.CYAN, Blocks.STAINED_GLASS_PANE.cyan());
        STAINED_GLASS_PANE.put(AllDyes.PURPLE, Blocks.STAINED_GLASS_PANE.purple());
        STAINED_GLASS_PANE.put(AllDyes.BLUE, Blocks.STAINED_GLASS_PANE.blue());
        STAINED_GLASS_PANE.put(AllDyes.BROWN, Blocks.STAINED_GLASS_PANE.brown());
        STAINED_GLASS_PANE.put(AllDyes.GREEN, Blocks.STAINED_GLASS_PANE.green());
        STAINED_GLASS_PANE.put(AllDyes.RED, Blocks.STAINED_GLASS_PANE.red());
        STAINED_GLASS_PANE.put(AllDyes.BLACK, Blocks.STAINED_GLASS_PANE.black());
        STAINED_GLASS_PANE.put(AllDyes.AMBER, BlockRegistry.AMBER_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.AQUA, BlockRegistry.AQUA_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.INDIGO, BlockRegistry.INDIGO_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.MAROON, BlockRegistry.MAROON_STAINED_GLASS_PANE);

        FROGLIGHT.put(AllDyes.WHITE, BlockRegistry.CLEAR_FROGLIGHT);
        FROGLIGHT.put(AllDyes.ORANGE, BlockRegistry.MANDARIN_FROGLIGHT);
        FROGLIGHT.put(AllDyes.MAGENTA, BlockRegistry.THULIAN_FROGLIGHT);
        FROGLIGHT.put(AllDyes.LIGHT_BLUE, BlockRegistry.CERULEAN_FROGLIGHT);
        FROGLIGHT.put(AllDyes.YELLOW, BlockRegistry.LEMON_FROGLIGHT);
        FROGLIGHT.put(AllDyes.LIME, BlockRegistry.KIWI_FROGLIGHT);
        FROGLIGHT.put(AllDyes.PINK, BlockRegistry.SAKURA_FROGLIGHT);
        FROGLIGHT.put(AllDyes.GRAY, BlockRegistry.CASCADING_FROGLIGHT);
        FROGLIGHT.put(AllDyes.LIGHT_GRAY, BlockRegistry.CLOUDY_FROGLIGHT);
        FROGLIGHT.put(AllDyes.CYAN, BlockRegistry.TEAL_FROGLIGHT);
        FROGLIGHT.put(AllDyes.PURPLE, Blocks.PEARLESCENT_FROGLIGHT);
        FROGLIGHT.put(AllDyes.BLUE, BlockRegistry.NAVY_FROGLIGHT);
        FROGLIGHT.put(AllDyes.BROWN, BlockRegistry.CHAMOISEE_FROGLIGHT);
        FROGLIGHT.put(AllDyes.GREEN, Blocks.VERDANT_FROGLIGHT);
        FROGLIGHT.put(AllDyes.RED, BlockRegistry.VERMILION_FROGLIGHT);
        FROGLIGHT.put(AllDyes.BLACK, BlockRegistry.CLOUDBURST_FROGLIGHT);
        FROGLIGHT.put(AllDyes.AMBER, Blocks.OCHRE_FROGLIGHT);
        FROGLIGHT.put(AllDyes.AQUA, BlockRegistry.SEAFOAM_FROGLIGHT);
        FROGLIGHT.put(AllDyes.INDIGO, BlockRegistry.LAVENDER_FROGLIGHT);
        FROGLIGHT.put(AllDyes.MAROON, BlockRegistry.SANGUINE_FROGLIGHT);

        SHULKER_BOX.put(AllDyes.WHITE, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.ORANGE, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.MAGENTA, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.LIGHT_BLUE, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.YELLOW, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.LIME, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.PINK, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.GRAY, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.LIGHT_GRAY, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.CYAN, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.PURPLE, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.BLUE, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.BROWN, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.GREEN, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.RED, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.BLACK, Blocks.SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.AMBER, BlockRegistry.AMBER_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.AQUA, BlockRegistry.AQUA_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.INDIGO, BlockRegistry.INDIGO_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.MAROON, BlockRegistry.MAROON_SHULKER_BOX);

        BED.put(AllDyes.WHITE, Blocks.BED.white());
        BED.put(AllDyes.ORANGE, Blocks.BED.orange());
        BED.put(AllDyes.MAGENTA, Blocks.BED.magenta());
        BED.put(AllDyes.LIGHT_BLUE, Blocks.BED.lightBlue());
        BED.put(AllDyes.YELLOW, Blocks.BED.yellow());
        BED.put(AllDyes.LIME, Blocks.BED.lime());
        BED.put(AllDyes.PINK, Blocks.BED.pink());
        BED.put(AllDyes.GRAY, Blocks.BED.gray());
        BED.put(AllDyes.LIGHT_GRAY, Blocks.BED.lightGray());
        BED.put(AllDyes.CYAN, Blocks.BED.cyan());
        BED.put(AllDyes.PURPLE, Blocks.BED.purple());
        BED.put(AllDyes.BLUE, Blocks.BED.blue());
        BED.put(AllDyes.BROWN, Blocks.BED.brown());
        BED.put(AllDyes.GREEN, Blocks.BED.green());
        BED.put(AllDyes.RED, Blocks.BED.red());
        BED.put(AllDyes.BLACK, Blocks.BED.black());
        BED.put(AllDyes.AMBER, BlockRegistry.AMBER_BED);
        BED.put(AllDyes.AQUA, BlockRegistry.AQUA_BED);
        BED.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BED);
        BED.put(AllDyes.MAROON, BlockRegistry.MAROON_BED);
    }
}
